meses-historico: 3

spring.datasource.url: jdbc:mysql://localhost:3306/incidencias
spring.datasource.username: Admin
spring.datasource.password: admin
spring.jpa.properties.jakarta.persistence.schema-generation.database.action: drop-and-create